
<select ng-change="check_valid()" name="nbd-field[<?php echo $field['id']; ?>][sub_value]" class="nbo-dropdown" ng-model="nbd_fields['<?php echo $field['id']; ?>'].sub_value">
<?php foreach ($attr['sub_attributes'] as $skey => $sattr): ?>
    <option value="<?php echo $skey; ?>" 
        <?php 
            if( isset($form_values[$field['id']]) && isset($form_values[$field['id']]['sub_value']) ){
                if ( $form_values[$field['id']]['sub_value'] == $skey ) echo 'selected="selected"';
            }else{
                if ( isset($sattr['selected']) ? $sattr['selected'] : 'off' == 'on' ) echo 'selected="selected"';
            }
        ?>><?php echo $sattr['name']; ?></option>
<?php endforeach; ?>
</select>

