<?php
/**
 * @author Netbaseteam Team
 * @copyright Copyright (c) 2018 Cmsmart (http://www.cmsmart.net)
 * @package Netbaseteam_Onestepcheckout
 */
?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\Options */ ?>

<?php $_options = $block->decorateArray($block->getOptions()) ?>
<?php if (count($_options)):?>
    <?php foreach ($_options as $_option): ?>
        <?php echo $block->getOptionHtml($_option) ?>
    <?php endforeach; ?>
<?php endif; ?>
