<?php 
	$datas = $block->getVisitor();
	$labely = array_values($datas);
	$labelx = array_keys($datas);

    $y = json_encode($labely);
    $x = json_encode($labelx);         
?>
<div class="dashboard-diagram-switcher">
    <div class="diagram-title">
        <h4>Visitor</h4>
        <span>monthly stats...</span>
    </div>
</div>
<div style="width:100%" class="customer-visitor-chart">
    <div>
        <canvas id="visitor" height="280" width="600"></canvas>
    </div>
</div>
<script type="text/javascript">
    require(['jquery','our_chart'], function($){
        
            var lineChartData = {
                labels : <?php echo $x; ?>,
                datasets : [
                    {
                        label: "My Second dataset",
                        fillColor: "rgba(248,159,159,0.8)",
                        strokeColor: "rgba(248,159,159,1)",
                        pointColor: "rgba(248,159,159,1)",
                        pointStrokeColor: "#fff",
                        pointHighlightFill: "#fff",
                        pointHighlightStroke: "rgba(248,159,159,1)",
                        data : <?php echo $y; ?>
                    }
                ]
            }
            var ctx = document.getElementById("visitor").getContext("2d");
            window.myLine = new Chart(ctx).Line(lineChartData, {
                responsive: true,
                scaleFontFamily: "'Open Sans'",
                tooltipTitleFontFamily: "'Open Sans'"
            });
    });
</script>