<?php
/**
 * @author Netbaseteam Team
 * @copyright Copyright (c) 2018 Cmsmart (http://www.cmsmart.net)
 * @package Netbaseteam_Onestepcheckout
 */
?>
<?php /** @var \Netbaseteam\Onestepcheckout\Block\Adminhtml\Sales\Order\Delivery $block */ ?>
<?php if ($fields = $block->getDeliveryDateFields()): ?>
<section class="admin__page-section netbaseteam-deliverydate">
    <div class="admin__page-section-title">
        <span class="title"><?= __('Delivery Information') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item" style="width: 49%;">
            <table class="admin__table-secondary">
                <?php foreach ($fields as $field): ?>
                    <tr>
                        <td><?= $field['label']; ?></td>
                        <td style="text-align: right;"><?= $field['value']; ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
</section>
<?php endif ?>
