<?php
    /**
     * Copyright © 2013-2017 Magento, Inc. All rights reserved.
     * See COPYING.txt for license details.
     */
    use Magento\Framework\App\Action\Action;
    
    // @codingStandardsIgnoreFile
    
    ?>
<?php
    /**
     * Product list template
     *
     * @var $block \Magento\Catalog\Block\Product\ListProduct
     */
    ?>
<?php
    $_productCollection = $block->getLoadedProductCollection();
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php
    $objectManagerr = \Magento\Framework\App\ObjectManager::getInstance();
    $objBlockk = $objectManagerr->get('\Netbaseteam\Calculatorshipping\Block\Calculatorshipping');
?>
<?php if (!$_productCollection->count()): ?> 
<div class="message info empty">
    <div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div>
</div>
<?php else: ?>
<div class="toolbar-top">
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
</div>
<?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
<div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
    <?php $iterator = 1; ?>
    <ol class="products list items product-items">
        <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
        <?php foreach ($_productCollection as $_product): ?>
        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
        <div class="product-item-info" data-container="product-grid">
            <?php
                $productImage = $block->getImage($_product, $image);
                if ($pos != null) {
                    $position = ' style="left:' . $productImage->getWidth() . 'px;'
                        . 'top:' . $productImage->getHeight() . 'px;"';
                }
                ?>
            <?php // Product Image ?>
            <div class="product-item-actions-wrap">
                <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                <?php echo $productImage->toHtml(); ?>
                </a>
                <?php if ($viewMode == 'grid') :?>
                    <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                        <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>> 
                            <?php if($objBlockk->_EnableModule()) : ?>
                                <div class="calculator actions-all">
                                    <a data-product-id="<?php echo $_product->getId(); ?>" class="netbase-calculator netbase_calculator_button netbase-calculator-button" title="Calculator Shipping" >
                                        <span><i class="icon-truck-1" style="font-size: 18px;"></i></span></a>
                                </div>
                            <?php endif ?>
                            <?php if ($_product->isSaleable()): ?>
                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                            <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                <?php echo $block->getBlockHtml('formkey')?>
                                <button type="submit"
                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                    class="action tocart primary">
                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                </button>
                            </form>
                            <?php else: ?>
                            <?php if ($_product->getIsSalable()): ?>
                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                            <?php else: ?>
                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                            <?php endif; ?>
                            <?php endif; ?>
                        </div>
                        <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                            <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                            <?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
                            <?php endif; ?>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
            <div class="product details product-item-details">
                <?php
                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                ?>
                <?php if ($viewMode == 'list') :?>
                    <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                <?php endif; ?>
                <strong class="product name product-item-name">
                <a class="product-item-link"
                    href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                <?php /* @escapeNotVerified */ echo substr($_helper->productAttribute($_product, $_product->getName(), 'name'),0,30); ?>
                </a>
                </strong>
                <?php if ($viewMode == 'list') :?>
                    <?php echo $block->getProductDetailsHtml($_product); ?>
                    <?php $shortDesc = substr($_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'),0,60) ?>
                <?php endif; ?>
                <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?> 
                <?php if ($viewMode == 'grid') :?>
                    <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                <?php endif; ?>

               
                <?php if ($viewMode == 'grid') :?>
                    <?php echo $block->getProductDetailsHtml($_product); ?>
                    <?php $shortDesc = substr($_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'),0,60) ?> 
                <?php endif; ?>
                <?php if (($showDescription) && ($viewMode == 'grid')) :?>
                <div class="product description product-item-description">
                    <?php /* @escapeNotVerified */ echo $shortDesc ?> 
                </div>
                <?php endif; ?>   
                <div class="product-item-inner">
                    <?php if ($viewMode == 'list') :?>
                        <div class="product description product-item-description">
                            <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>                                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
                                class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                        </div>
                        <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                            <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>> 
                                <?php if ($_product->isSaleable()): ?>
                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                    <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                    <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                    <?php echo $block->getBlockHtml('formkey')?>
                                    <button type="submit"
                                        title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                        class="action tocart primary">
                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                    </button>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                    <?php if($objBlockk->_EnableModule()) : ?> 
                                        <a data-product-id="<?php echo $_product->getId(); ?>" class="action netbase-calculator netbase_calculator_button netbase-calculator-button" title="Calculator Shipping" >
                                            <i class="icon-truck-1" style="font-size: 18px;"></i>
                                        </a> 
                                    <?php endif ?>
                                    <?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
                                    <?php endif; ?>
                                </form>
                                <?php else: ?>
                                <?php if ($_product->getIsSalable()): ?>
                                <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                <?php else: ?>
                                <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                <?php endif; ?>
                                <?php endif; ?> 
                            </div> 
                        </div> 
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
        <?php endforeach; ?>
    </ol>
</div>
<?php echo $block->getToolbarHtml() ?>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {}
        }
    }
</script>
<?php endif; ?>
<?php endif; ?>