<?php
$jsonHelper = $this->helper('Magento\Framework\Json\Helper\Data');
$max_input_vars = abs( intval( ini_get( 'max_input_vars' ) ) );
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$resource = $objectManager->get('\Magento\Framework\Module\ResourceInterface');
$version = $resource->getDbVersion('Netbaseteam_PricingOption');
$options = $this->getPricingOptions();
$default_field = $this->getDefaultConfigField();
$imageHelper = $objectManager->get('Magento\Catalog\Helper\Image');
$placeholder = $imageHelper->getDefaultPlaceholderUrl('image');
?>
<div class="nbd-field-info">
    <div class="nbd-field-info-1">
        <div><label><b><?php echo __('Display type'); ?></b></label></div>
    </div>
    <div class="nbd-field-info-2">
        <div>
            <select convert-to-number name="options[display_type]" ng-model="options.display_type">
                <option <?php echo $options['display_type'] == 1 ? 'selected' : ''?> value="1"><?php echo __('Default'); ?></option>
                <option <?php echo $options['display_type'] == 2 ? 'selected' : ''?> value="2"><?php echo __('Price Matrix'); ?></option>
                <option <?php echo $options['display_type'] == 4 ? 'selected' : ''?> value="4"><?php echo __('Group'); ?></option>
                <option <?php echo $options['display_type'] == 5 ? 'selected' : ''?> value="5"><?php echo __('Step by step'); ?></option>
            </select>
        </div>
    </div>
</div>
<div class="nbd-field-info" ng-if="options.display_type == 2">
    <p><?php echo __('Allow fields with options: Data type - Multiple options | Enable - Yes | has at least one attribute | Field Conditional Logic - No'); ?></p>
    <div class="nbd-field-info">
        <div class="nbd-field-info-1">
            <div><label><b><?php echo __('Horizontal field'); ?></b></label></div>
        </div>
        <div class="nbd-field-info-2">
            <div>
                <select name="options[pm_hoz][]" multiple ng-model="options.pm_hoz">
                    <option value="{{field.field_index}}" ng-repeat="(fieldIndex, field) in availablePmHozFileds">{{options.fields[field.field_index].general.title.value}}</option>
                </select>
            </div>
        </div>    
    </div>   
    <div class="nbd-field-info">
        <div class="nbd-field-info-1">
            <div><label><b><?php echo __('Vertical field'); ?></b></label></div>
        </div>
        <div class="nbd-field-info-2">
            <div>
                <select name="options[pm_ver][]" multiple ng-model="options.pm_ver">
                    <option  value="{{field.field_index}}" ng-repeat="(fieldIndex, field) in availablePmVerFileds">{{options.fields[field.field_index].general.title.value}}</option>
                </select>                        
            </div>
        </div>    
    </div> 
    <div class="nbd-field-info">
        <table>
            <tbody>
                <tr></tr>
            </tbody>
        </table>
    </div>    
</div>
<div class="nbd-field-info" ng-if="options.display_type == 3">
    <p><?php echo __('Allow fields with options: Enable - Yes | Field Conditional Logic - No'); ?></p>
    <div class="nbd-field-info">
        <div class="nbd-field-info-1">
            <div><label><b><?php echo __('Bulk form field'); ?></b></label></div>
        </div>
        <div class="nbd-field-info-2">
            <div>
                <select name="options[bulk_fields][]" multiple ng-model="options.bulk_fields">
                    <option value="{{field.field_index}}" ng-repeat="(fieldIndex, field) in availableBulkFileds">{{options.fields[field.field_index].general.title.value}}</option>
                </select>
            </div>
        </div>    
    </div>    
</div>
<div class="nbd-field-info" ng-show="options.display_type == 4">
    <p><b><?php echo __('Manage option groups'); ?></b></p>
    <div ng-repeat="(gIndex, group) in options.groups" class="nbd-group-wrap">
        <div class="nbd-group-img-wrap" ng-show="group.isExpand">
            <label><?php echo __('Icon'); ?></label>
            <div class="nbd-group-img-inner">
                <?php $unique = uniqid('option-image-');?>
                <span class="dashicons dashicons-no remove-group-img" ng-click="remove_group_image( $index )"></span>
                <input id="<?php echo $unique?>-{{$index}}" ng-hide="true" ng-model="group.image" name="options[groups][{{$index}}][image]" ng-change="attach_group_image($index)"/>
                <img title="<?php echo __('Click to change image'); ?>" ng-click="set_group_image( $index ,'<?php echo $block->getUrl('cms/wysiwyg_images/index').'element_name/pricingoption-image/target_element_id/'.$unique?>')" ng-src="{{group.image != 0 ? group.image : '<?php echo $placeholder ?>'}}" />
            </div>
        </div>
        <div class="nbd-group-main" ng-show="group.isExpand">
            <div class="group-field">
                <label><?php echo __('Title'); ?></label>
                <input type="text" ng-model="group.title" name='options[groups][{{$index}}][title]' />
            </div>
            <div class="group-field">
                <label><?php echo __('Description'); ?></label>
                <textarea ng-model="group.des" value="{{group.des}}" name='options[groups][{{$index}}][des]' rows="5"></textarea>
            </div>
            <div class="group-field">
                <label><?php echo __('Note'); ?></label>
                <textarea ng-model="group.note" value="{{group.note}}" name='options[groups][{{$index}}][note]' rows="5"></textarea>
            </div>
            <div class="group-field">
                <label><?php echo __('Number of column'); ?></label>
                <select ng-model="group.cols" name='options[groups][{{$index}}][cols]' convert-to-number>
                    <option value="1">1 <?php echo __('Column'); ?></option>
                    <option value="2">2 <?php echo __('Columns'); ?></option>
                    <option value="3">3 <?php echo __('Columns'); ?></option>
                    <option value="4">4 <?php echo __('Columns'); ?></option>
                </select>
            </div>
            <div class="group-field">
                <label><?php echo __('Group field list'); ?></label>
                <select name="options[groups][{{$index}}][fields][]" multiple ng-model="group.fields">
                    <option value="{{field.id}}" ng-repeat="field in options.fields | filter: {id: gIndex}:availableGroupField">{{field.general.title.value}}</option>
                </select>
                <p><a class="button" ng-click="clear_group($index)"><span class="dashicons dashicons-no-alt"></span><?php echo __('Clear all group fields') ?></a></p>
            </div>
        </div> 
        <div ng-show="!group.isExpand" class="nbd-group-name-preview">{{group.title}}</div>
        <div class="nbd-group-actions">
            <span class="nbo-sort-group">
                <span ng-click="sort_group($index, 'up')" class="dashicons dashicons-arrow-up nbo-sort-up nbo-sort" title="<?php echo __('Up') ?>"></span>
                <span ng-click="sort_group($index, 'down')" class="dashicons dashicons-arrow-down nbo-sort-down nbo-sort" title="<?php echo __('Down') ?>"></span>
            </span>
            <a class="button nbd-mini-btn" ng-click="remove_group($index)" title="<?php echo __('Delete'); ?>"><span class="dashicons dashicons-no-alt"></span></a>
            <a class="button nbd-mini-btn"  ng-click="toggle_expand_group($index)" title="<?php echo __('Expend'); ?>">
                <span ng-show="group.isExpand" class="dashicons dashicons-arrow-up"></span>
                <span ng-show="!group.isExpand" class="dashicons dashicons-arrow-down"></span>
            </a>
        </div>
    </div>
    <div>
        <a class="button" ng-click="add_group()"><span class="dashicons dashicons-plus"></span><?php echo __('Add group'); ?></a>
    </div>
</div>