<?php
    $jsonHelper = $this->helper('Magento\Framework\Json\Helper\Data');
    $max_input_vars = abs( intval( ini_get( 'max_input_vars' ) ) );
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $resource = $objectManager->get('\Magento\Framework\Module\ResourceInterface');
    $version = $resource->getDbVersion('Netbaseteam_PricingOption');
    $options = $this->getPricingOptions();
    $default_field = $this->getDefaultConfigField();
?>
<script type="text/javascript">
    var NBDOPTIONS = <?php echo $jsonHelper->jsonEncode($options); ?>;
    var NBDOPTION_FIELD = <?php echo $jsonHelper->jsonEncode($default_field); ?>;
    var max_input_vars = parseInt(<?php echo $max_input_vars; ?>);
    var ajax_url = "<?php echo $this->getUrl('pricingoption/option/ajax', array('_current'=>true)); ?>";
    var nbnonce = "93ca89e0d5";

    var nbd_options = {
        "nbd_options_lang": {
            "page": "Sides/Pages",
            "page1": "Number of Pages",
            "page2": "Side list",
            "page3": "Front/Back Sides",
            "color": "Color",
            "size": "Size",
            "dpi": "DPI",
            "area": "Area design shape",
            "orientation": "Orientation",
            "dimension": "Custom dimension",
            "padding": "Padding",
            "rounded_corner": "Rounded corner",
            "nbpb_com": "Component",
            "nbpb_text": "Text",
            "nbpb_image": "Image",
            "dpi_description": "DPI is used to describe the resolution number of dots per inch in a digital print and the pricing resolution of a hard copy print dot gain, which is the increase in the size of the halftone dots during pricing.",
            "vertical": "Vertical",
            "horizontal": "Horizontal",
            "can_not_add_att": "Can not add more attribute for this option.",
            "can_not_remove_att": "Can not remove this attribute.",
            "rectangle": "Rectangle",
            "ellipse": "Ellipse",
            "attribute_name": "Attribute name",
            "sub_attribute_name": "Sub attribute name",
            "can_not_copy": "Can not copy this option.",
            "option_exist": "This option exist.",
            "front": "Front side",
            "back": "Back side",
            "one_side": "1 side",
            "both": "Both sides",
            "want_to_delete": "Are you sure you want to delete this field?",
            "want_to_delete_all": "Are you sure you want to delete all fields?",
            "choose_image": "Choose Image",
            "view_name": "View name",
            "max_input_var": "PHP max input vars:",
            "max_input_notice": "Please increase \"PHP max input vars\"!",
            "group_title": "Group name",
            "group_des": "Group description",
            "group_note": "Group note",
            "delivery": "Delivery",
            "delivery_3_days": "3 days",
            "actions": "Artwork actions",
            "no_thank": "No thank you",
            "upload_design": "Upload your design",
            "create_your_own": "Create your design online",
            "hire_designer": "Want the experts design for you",
            "overlay": "Overlay",
            "fold": "Folding Styles",
            "frame": "Frame options",
            "number_file": "Number of upload files"
        },
        "calendar_image": "",
        "search_products_nonce": "93ca89e0d5"
    };
</script>

<div id="pricing_option_form_admin" class="wrap" ng-cloak>
    <div ng-controller="optionCtrl">
        <div id="poststuff">
            <div id="post-body" class="metabox-holder columns-2">
                <div id="postbox-container-1" class="postbox-container">
                    <div id="submitdiv" class="postbox ">
                        <h2 class="hndle ui-sortable-handle"><span><?php echo __('Publish'); ?></span></h2>
                        <div class="inside">
                            <div id="titlewrap">
                                <label class="screen-reader-text" id="title-prompt-text" for="title"><?php echo __('Title'); ?></label>
                                <input required="required" ng-model="options.title" type="text" name="title" size="30" value="<?php echo $options['title']; ?>" id="title" autocomplete="off">
                                <span style="color: red;" ng-show="nboForm.title.$invalid">* <small><i><?php echo __('required'); ?></i></small></span>
                                <input type="hidden" name="options[version]" value="<?php echo $version; ?>" />
                                <input type="hidden" name="store_id_hidden" value="" />
                            </div>
                            <div class="submitbox" id="submitpost">
                                <div id="minor-publishing">
                                    <div id="misc-publishing-actions">
                                        <div class="misc-pub-section misc-pub-published" id="published">
                                            <?php echo __('Published'); ?>
                                            <select name="published">
                                                <option value="1" <?php echo $options['published'] == 1 ? 'selected' : '' ?>>Yes</option>
                                                <option value="0" <?php echo $options['published'] == 0 ? 'selected' : '' ?>>No</option>
                                            </select>                                 
                                        </div>
                                        <div class="misc-pub-section misc-pub-priority" id="priority">
                                            <?php echo __('Priority'); ?>
                                            <input type="number" value="<?php echo $options['priority']; ?>" maxlength="3" max="127"
                                                id="nbo_meta_priority" name="priority" class="meta-priority" min="1"
                                                step="1"/>                                    
                                        </div>
                                    </div>
                                    <div class="clear"></div>
                                </div>  
                                <div class="minor-publishing">
                                    <div class="misc-publishing-actions nbo-dates" >
                                        <div style="margin-bottom: 15px;">
                                            <label for="date_from"><?php echo __('From'); ?></label>
                                            <input type="text" class="date_from datepicker" id="date_from" name="date_from" value="<?php echo $options['date_from']; ?>" placeholder="<?php echo __('YYYY-MM-DD'); ?>" title="<?php echo __('Leave both fields blank to not restrict this options to a date range'); ?>"/>
                                        </div>
                                        <div>
                                            <label for="date_to"><?php echo __('To'); ?></label>
                                            <input class="date_to datepicker" id="date_to" name="date_to" value="<?php echo $options['date_to']; ?>" placeholder="<?php echo __('YYYY-MM-DD'); ?>" title="<?php echo __('Leave both fields blank to not restrict this options to a date range'); ?>"/>
                                        </div>    
                                    </div>  
                                    <div class="clear"></div>
                                </div>
                            </div>
                        </div>                        
                    </div>

                    <div id="notice-max-input-vars" class="postbox" ng-show="current_input_vars > max_input_vars">
                        <h2 style="color: #ff4136;" class="hndle ui-sortable-handle"><span style="vertical-align: bottom; margin-top: 0;" class="dashicons dashicons-warning"></span> <span><?php echo __('Notice'); ?></span></h2>
                        <div class="inside">
                            <p><?php echo __('PHP max input vars:'); ?> <?php echo $max_input_vars; ?></p>
                            <p><?php echo __('Current input vars:'); ?> <span>{{current_input_vars}}</span></p>
                            <p><?php echo __('Please increase "PHP max input vars"!'); ?></p>
                        </div>
                    </div>
                </div>
                <div id="postbox-container-2" class="postbox-container">
                    <div class="postbox">
                        <div class="inside">
                            <div class="nbd-option-actions">
                                <a ng-click="import()" class="button-primary"><span class="dashicons dashicons-migrate nbd-r180"></span> <?php echo __('Import'); ?></a>
                                <a ng-click="export()" class="button-primary"><span class="dashicons dashicons-migrate"></span> <?php echo __('Export'); ?></a>
                            </div> 
                        </div>    
                    </div>                    
                    <div class="postbox nbd-fields-wrap"> 
                        <h2 style="border-bottom: 1px solid #ddd;"><?php echo __('Pricing fields'); ?></h2>
                        <div class="inside">
                            <div>
                                <p class="section-title"><input class="nbd-ip-readonly" value="<?php echo __('Default field'); ?>" readonly=""></p>
                                <div class="nbd-section-wrap">
                                    <a title="<?php echo __('Add fields'); ?>" class="nbd-field-btn button" ng-click="add_field()"><?php echo __('Default field'); ?> <span class="nbo-type-label default">1</span></a>
                                    <a title="<?php echo __('Add fields'); ?>" class="nbd-field-btn button" ng-click="add_field('delivery')"><?php echo __('Delivery date'); ?> <span class="nbo-type-label default">30</span></a>
                                    <a title="<?php echo __('Artwork actions'); ?>" class="nbd-field-btn button" ng-click="add_field('actions')"><?php echo __('Artwork actions'); ?> <span class="nbo-type-label default">31</span></a>
                                </div>
                            </div>
                            <div style="margin-top: 10px;">
                                <p class="section-title"><input class="nbd-ip-readonly" value="<?php echo __('Online design fields'); ?>" readonly=""></p>
                                <div class="nbd-section-wrap">
                                    <a class="nbd-field-btn button" ng-click="add_field('page')"><?php echo __('Sides/Pages'); ?> <span class="nbo-type-label wod">2</span></a>
                                    <a class="nbd-field-btn button" ng-click="add_field('page1')"><?php echo __('Number of Pages'); ?> <span class="nbo-type-label wod">2.1</span></a>
                                    <a class="nbd-field-btn button" ng-click="add_field('page2')"><?php echo __('Side list'); ?> <span class="nbo-type-label wod">2.2</span></a>
                                    <a class="nbd-field-btn button" ng-click="add_field('page3')"><?php echo __('Front/Back Sides'); ?> <span class="nbo-type-label wod">2.3</span></a>
                                    <a class="nbd-field-btn button" ng-click="add_field('color')"><?php echo __('Color/Material'); ?> <span class="nbo-type-label wod">3</span></a>
                                    <a class="nbd-field-btn button" ng-click="add_field('size')"><?php echo __('Size'); ?> <span class="nbo-type-label wod">4</span></a>
                                    <a class="nbd-field-btn button" ng-click="add_field('dimension')"><?php echo __('Custom dimension'); ?> <span class="nbo-type-label wod">5</span></a>
                                    <a class="nbd-field-btn button" ng-click="add_field('dpi')"><?php echo __('DPI'); ?> <span class="nbo-type-label wod">6</span></a>
                                    <a class="nbd-field-btn button" ng-click="add_field('area')"><?php echo __('Area design shape'); ?> <span class="nbo-type-label wod">7</span></a>
                                    <a class="nbd-field-btn button" ng-click="add_field('orientation')"><?php echo __('Orientation'); ?> <span class="nbo-type-label wod">8</span></a>
                                    <a class="nbd-field-btn button" ng-click="add_field('padding')"><?php echo __('Padding'); ?> <span class="nbo-type-label wod">9</span></a>
                                    <a class="nbd-field-btn button" ng-click="add_field('rounded_corner')"><?php echo __('Rounded corners'); ?> <span class="nbo-type-label wod">10</span></a>
                                </div>
                            </div>
                            <div style="margin-top: 10px;">
                                <p class="section-title"><input class="nbd-ip-readonly" value="<?php echo __('Product builder fields'); ?>" readonly=""></p>
                                <div class="nbd-section-wrap">
                                    <a class="nbd-field-btn button" ng-click="add_field('nbpb_com', 'nbpb_com')"><?php echo __('Component'); ?> <span class="nbo-type-label wpo">20</span></a>
                                    <a class="nbd-field-btn button" ng-click="add_field('nbpb_text', 'nbpb_text')"><?php echo __('Text'); ?> <span class="nbo-type-label wpo">21</span></a>
                                    <a class="nbd-field-btn button" ng-click="add_field('nbpb_image', 'nbpb_image')"><?php echo __('Image'); ?> <span class="nbo-type-label wpo">22</span></a>
                                </div>
                            </div>
                            <div>
                                <p>
                                    <span class="nbo-type-label default">1</span> 
                                    <span class="nbo-type-label default">30</span> 
                                    <span class="nbo-type-label default">31</span> 
                                    <?php echo __('Default fields'); ?></p>
                                <p>
                                    <span class="nbo-type-label wod">2</span>
                                    <span class="nbo-type-label wod">3</span>
                                    <span class="nbo-type-label wod">4</span>
                                    <span class="nbo-type-label wod">5</span>
                                    <span class="nbo-type-label wod">6</span>
                                    <span class="nbo-type-label wod">7</span>
                                    <span class="nbo-type-label wod">8</span> 
                                    <span class="nbo-type-label wod">9</span> 
                                    <span class="nbo-type-label wod">10</span> 
                                    <?php echo __('Online design fields which effect custom design configuaration.'); ?>
                                </p>
                                <p>
                                    <span class="nbo-type-label wpo">20</span>
                                    <span class="nbo-type-label wpo">21</span>
                                    <span class="nbo-type-label wpo">22</span> 
                                    <?php echo __('Product builder fields'); ?>
                                </p>
                                <p>
                                    <span class="nbo-type-label" style="background:red">V</span>
                                    <?php echo __('Pricing options field and Appearance field will update when change store view'); ?>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="postbox">
                        <h2 style="border-bottom: 1px solid #ddd;"><?php echo __('Pricing options'); ?>
                            <span class="nbo-type-label" style="background:red;margin-left: 5px">V</span>
                        </h2>
                        <div class="inside">
                            <div class="nbd-fields-builder">
                                <?php echo $this->getLayout()->createBlock("Netbaseteam\PricingOption\Block\Adminhtml\Option\Edit\Renderer")->setTemplate("Netbaseteam_PricingOption::option/views/options/quantity.phtml")->toHtml() ?>
                                <?php echo $this->getLayout()->createBlock("Netbaseteam\PricingOption\Block\Adminhtml\Option\Edit\Renderer")->setTemplate("Netbaseteam_PricingOption::option/views/options/field.phtml")->toHtml() ?>
                            </div>
                            <div ng-repeat="view in options.views">
                                <input ng-hide="true" ng-model="view.name" name="options[views][{{$index}}][name]"/>
                                <input ng-hide="true" ng-model="view.base" name="options[views][{{$index}}][base]"/>
                                <input ng-hide="true" ng-model="view.base_width" name="options[views][{{$index}}][base_width]"/>
                                <input ng-hide="true" ng-model="view.base_height" name="options[views][{{$index}}][base_height]"/>
                            </div>
                        </div>    
                    </div>                    
                </div> 
                <div id="postbox-container-3" class="postbox-container">
                    <div class="postbox">
                        <h2 style="border-bottom: 1px solid #ddd;"><?php echo __('Appearance'); ?>
                            <span class="nbo-type-label" style="background:red;margin-left: 5px">V</span>
                        </h2>
                        <div class="inside">
                            <?php echo $this->getLayout()->createBlock("Netbaseteam\PricingOption\Block\Adminhtml\Option\Edit\Renderer")->setTemplate("Netbaseteam_PricingOption::option/views/options/appearance.phtml")->toHtml() ?>
                        </div>
                    </div>
                </div>    
            </div>
        </div>
        <div class="clear"></div>
    </div>
</div>
<div class="nbp-loading-wrap">
    <div class="nbp-loading-spinner">
        <div class="nbp-loading-ball"></div>
        <p id="nbp-processing" style="display: none;font-weight: bold;white-space: nowrap;"><?php echo __('Processing'); ?> <span id="nbp-process-loaded"></span> / <span id="nbp-process-total"></span></p>
    </div>
</div>

<script type="text/javascript">
    require([
        "jquery",
        "mage/calendar"
    ], function($){
        $('.datepicker').datepicker({
           prevText: '&#x3c;zurück', prevStatus: '',
            prevJumpText: '&#x3c;&#x3c;', prevJumpStatus: '',
            nextText: 'Vor&#x3e;', nextStatus: '',
            nextJumpText: '&#x3e;&#x3e;', nextJumpStatus: '',
            monthNames: ['Januar','Februar','März','April','Mai','Juni',
            'Juli','August','September','Oktober','November','Dezember'],
            showMonthAfterYear: false,
            dateFormat:'yy-mm-dd'
        });
    });
</script>

<script type="text/x-magento-init">
    {
        "*": {
            "admin-options": {},
            "angularjs": {}
        }
    }
</script>