<?php 
    $link_create_option = '';    
?>
<div class="wrap">
    <h1>
        <?php echo __('Pricing options'); ?>
        <a class="nbd-page-title-action" href="<?php echo $link_create_option; ?>"><?php echo __('Add new'); ?></a>
    </h1>
    <div id="poststuff">
        <div id="post-body" class="metabox-holder">
            <div id="post-body-content">
                <div class="meta-box-sortables ui-sortable">
                    <form method="post">
                    <?php
                        $nbd_options->prepare_items();
                        $nbd_options->display();
                    ?>
                    </form>
                </div>
            </div>
        </div>
        <br class="clear">
    </div>    
</div>
