<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>
<?php $_helper = $this->helper('Magento\Catalog\Helper\Output'); ?>
<?php $_product = $block->getProduct(); ?>

<div class="product-add-form <?php echo $_product->getData('has_upload_file') ? 'product-upload' : 'product-not-upload' ?>">
    <form data-product-sku="<?= /* @NoEscape */ $_product->getSku() ?>"
          action="<?= /* @NoEscape */ $block->getSubmitUrl($_product) ?>" method="post"
          id="product_addtocart_form"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $_product->getId() ?>" />
        <input type="hidden" name="selected_configurable_option" value="" />
        <input type="hidden" name="related_product" id="related-products-field" value="" />
        <input type="hidden" name="custom_option_price" id="custom_option_price" value="">
        <input type="hidden" name="custom_pricematrix_price" id="custom_pricematrix_price" value="">
        <?= $block->getBlockHtml('formkey') ?>
        <?= $block->getChildHtml('form_top') ?>

        <?php if ($_product->isSaleable() && $block->hasOptions()): ?>
            <?= $block->getChildHtml('product_options_wrapper') ?>
        <?php else: ?>
            <?= $block->getChildHtml('nb.pricematrix.contain') ?>
        <?php endif ?>


        <div class="product-add-form__action-box">
            <?php if (!$block->hasOptions()):?>
                <?= $block->getChildHtml('product_info_form_content') ?>
            <?php else:?>
                <?php if ($_product->isSaleable() && $block->getOptionsContainer() == 'container1'):?>
                    <?= $block->getChildChildHtml('options_container') ?>
                <?php endif;?>
            <?php endif; ?>

            <?php if ($_product->isSaleable() && $block->hasOptions() && $block->getOptionsContainer() == 'container2'):?>
                <?= $block->getChildChildHtml('options_container') ?>
            <?php endif;?>
            <?= $block->getChildHtml('form_bottom') ?>
        </div>
    </form>
    <?= $block->getChildHtml('product_info_nb_additional') ?>
</div>

<script>
    require([
        'jquery',
        'priceBox'
    ], function($){
        var dataPriceBoxSelector = '[data-role=priceBox]',
            dataProductIdSelector = '[data-product-id=<?= $block->escapeHtml($_product->getId()) ?>]',
            priceBoxes = $(dataPriceBoxSelector + dataProductIdSelector);

        priceBoxes = priceBoxes.filter(function(index, elem){
            return !$(elem).find('.price-from').length;
        });

        priceBoxes.priceBox({'priceConfig': <?= /* @escapeNotVerified */ $block->getJsonConfig() ?>});
    });
</script>
