<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */


?>
<?php
/**
 * @see \Magento\Sales\Block\Adminhtml\Items\Column\Name
 */
?>

<?php if ($_item = $block->getItem()): ?>
    <div id="order_item_<?= $block->escapeHtml($_item->getId()) ?>_title"
         class="product-title">
        <?= $block->escapeHtml($_item->getName()) ?>
    </div>
    <div class="product-sku-block">
        <span><?= $block->escapeHtml(__('SKU'))?>:</span> <?= implode('<br />', $this->helper('Magento\Catalog\Helper\Data')->splitSku($block->escapeHtml($block->getSku()))) ?>
    </div>

    <?php if ($block->getOrderOptions()): ?>
        <dl class="item-options">
            <?php foreach ($block->getOrderOptions() as $_option): ?>
                <dt><?= $block->escapeHtml($_option['label']) ?>:</dt>
                <dd>
                    <?php if (isset($_option['custom_view']) && $_option['custom_view']): ?>
                        <?= /* @escapeNotVerified */ $block->getCustomizedOptionValue($_option) ?>
                    <?php else: ?>
                        <?php if(isset($_option['is_upload']) && $_option['is_upload']):?>
                            <a href="<?php echo $this->helper('\Netbaseteam\PricingOption\Helper\Data')->getBaseUrlUpload().'/'.'pricing_options/'.$_option['value']; ?>"><?php echo $_option['value']?></a>
                            <?php if(isset($_option['price']) && $_option['price']):?>
                                <span class="price"> +<?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency(number_format($_option['price'],2),true,false);?></span>
                            <?php endif;?>
                        <?php else:?>
                            <?php if(isset($_option['price']) && $_option['price']):?>
                                <span class="price"> +<?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency(number_format($_option['price'],2),true,false);?></span>
                            <?php endif;?>
                            <?php $_option = $block->getFormattedOption($_option['value']); ?>
                            <?php $dots = 'dots' . uniqid(); ?>
                            <?= $block->escapeHtml($_option['value']) ?><?php if (isset($_option['remainder']) && $_option['remainder']): ?> <span id="<?= /* @noEscape */ $dots; ?>"> ...</span>
                                <?php  $id = 'id' . uniqid(); ?>
                                <span id="<?= /* @noEscape */ $id; ?>"><?= $block->escapeHtml($_option['remainder']) ?></span>
                                <script>
                                    require(['prototype'], function() {
                                        $('<?= /* @noEscape */ $id; ?>').hide();
                                        $('<?= /* @noEscape */ $id; ?>').up().observe('mouseover', function(){$('<?= /* @noEscape */ $id; ?>').show();});
                                        $('<?= /* @noEscape */ $id; ?>').up().observe('mouseover', function(){$('<?= /* @noEscape */ $dots; ?>').hide();});
                                        $('<?= /* @noEscape */ $id; ?>').up().observe('mouseout',  function(){$('<?= /* @noEscape */ $id; ?>').hide();});
                                        $('<?= /* @noEscape */ $id; ?>').up().observe('mouseout',  function(){$('<?= /* @noEscape */ $dots; ?>').show();});
                                    });
                                </script>
                            <?php endif; ?>
                        <?php endif;?>
                    <?php endif; ?>
                </dd>
            <?php endforeach; ?>
        </dl>
    <?php endif; ?>
    <?= $block->escapeHtml($_item->getDescription()) ?>
<?php endif; ?>
