<?php
/**
 * @copyright Copyright (c) 2016 www.cmsmart.net
 */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$request = $objectManager->get('Magento\Framework\App\Action\Context')->getRequest();
$objBlock = $objectManager->get('\Netbaseteam\Calculatorshipping\Block\Calculatorshipping');
?>
<?php if($block->_EnableModule()) : ?>
    <!-- For please wait -->
    <div id="nb-estshipping-cost-loading" class="blockestshipping-cost-popup-none" style="display: none;"></div>
    <!-- For show product options -->
    <div id="estshippingcost_content_option_product" class="blockestshipping-cost-popup-none" style="display: none;" >
        <div class="est_option_title">
            <p><?php echo $objBlock->_getPopupTitle(); ?></p>
            <button type="button" title="Cancel" class="action primary" id="estshippingcost_cancel">
                <span><?php echo __('x') ?></span>
            </button>
        </div>
        <div class="est_option_content"></div>
    </div>
    <div class="estshipping-cost-popup-none" id="estshipping-cost-shadow" style="z-index:9998;"></div>
<?php endif; ?>