<?php $_themeconfig = $this->getCollection(); ?>
<?php if ($_themeconfig->getSize()): ?>
<div class="themeconfig_list_view">
    <?php foreach ($_themeconfig as $themeconfigItem): ?>
        <div id="item_<?php echo $themeconfigItem->getId() ?>" class="themeconfig_list_item">
            <h2>
                <a href="<?php echo $this->getItemUrl($themeconfigItem) ?>">
                    <?php echo $this->escapeHtml($themeconfigItem->getTitle()) ?>
                </a>
            </h2>

            <div class="themeconfig_item_subtitle">
                <?php echo $this->formatDate($themeconfigItem->getPublishedAt()) ?> |
                <?php echo $this->escapeHtml($themeconfigItem->getAuthor()) ?>
            </div>

            <?php if ($imageUrl = $this->getImageUrl($themeconfigItem, 100)): ?>
               <p><img src="<?php echo $imageUrl ?>" alt="<?php echo $this->escapeHtml($themeconfigItem->getTitle()); ?>" /></p>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
</div>
<?php echo $this->getPager() ?>
<?php else: ?>
    <div class="message info empty"><span><?php echo __('You have no Themeconfig.'); ?></span></div>
<?php endif ?>
