<?php
/**
 * Themeconfig template for separate item
 *
 */

/**
 * @var $this Netbaseteam\Themeconfig\Block\View
 * @see Netbaseteam\Themeconfig\Block\View
 */
?>
<?php $_themeconfigItem = $this->getThemeconfig(); ?>
    <div class="themeconfig_item_subtitle">
        <?php echo $this->formatDate($_themeconfigItem->getPublishedAt()) ?> |
        <?php echo $this->escapeHtml($_themeconfigItem->getAuthor()) ?>
    </div>

<div class="themeconfig_item_view">
    <?php if ($imageUrl = $this->getImageUrl($_themeconfigItem, 400)): ?>
       <p><img src="<?php echo $imageUrl ?>" alt="<?php echo $this->escapeHtml($_themeconfigItem->getTitle()) ?>" /></p>
    <?php endif; ?>

    <div class="themeconfig_item_content"><?php echo $_themeconfigItem->getContent() ?></div>

    <div class="pager">
        <a href="<?php echo $this->getBackUrl() ?>">
            <?php echo __('Return to list') ?>
        </a>
    </div>
</div>