<?php
    /**
    * Copyright © 2016 SW-THEMES. All rights reserved.
    */
    use Magento\Framework\App\Action\Action;
    
    // @codingStandardsIgnoreFile
    ?>
<?php
    $showWishlist = true;
    $showCompare = true;
    $_helper = $this->helper('Netbase\Product\Helper\Data');
    $config = $_helper->getConfig("pro_bestseller/general");
    $categories = explode(',', $config['categories']);
    $title = $_helper->getTitle('pro_bestseller/general/title');
    $currentSymbol = $_helper->getCurrencySymbol();
    $banner = $_helper->getBanner('pro_bestseller/general/banner'); 
    $tabs = $_helper->getAllTabs('pro_bestseller/general/categories', 'best-tab-');
    ?>
<section class="bestseller-product home-product-tab section-print3">
    <div class="container">
        <div class="heading">
            <h5><?php echo __('Featured product') ?></h5>
            <h2><?php echo __('Things We Know You&#39;ll Love') ?></h2>
            <div class="rule"></div>
            <p>Love to see a photo print on mug, you are in the right place. Photo printing on mugs is made extremely easy with the customization and design process we have put in place.</p>
        </div>
        <div class="home-product-tab-content section-content">
            <?php
                foreach($categories as $categoryId):  
                $productCollection = $block->getProductCollection($categoryId);  
                ?> 
                <div class="home-product-slider products-grid nb-list">
                    <ol class="list items product-items row display-clear">
                        <?php
                            $i=0; foreach ($productCollection as $_product):
                            ?>
                            <li class="product item col-sm-6 col-md-3 col-lg-3">
                                <div class="product-item-info" data-container="product-grid">
                                    <?php      
                                        $originalPrice = $_product->getPrice();  //200 
                                        $specialPrice = $_product->getSpecialPrice();  
                                        ?>
                                    <?php if(($specialPrice)&&($specialPrice <= $originalPrice)){?> 
                                    <div class="sale">
                                        <span> 
                                        <?php
                                            $saleof= abs(($specialPrice/($originalPrice))*100-100);
                                            echo '- ';    
                                            print_r(floor($saleof));
                                            echo '%'; 
                                            ?>                                   
                                        </span> 
                                    </div>
                                    <?php } ?>
                                    <?php
                                        $image = 'category_page_grid' or 'category_page_list';
                                        $_imagehelper = $this->helper('Magento\Catalog\Helper\Image'); 
                                        $productImage = $_imagehelper->init($_product, $image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(250)->getUrl();
                                        ?>
                                    <div class="product-item-actions-wrap">
                                        <a href="<?php echo $_product->getProductUrl() ?>" class="product photo product-item-photo display-flex" tabindex="-1">
                                        <img alt="" src="<?php echo $productImage; ?>" />
                                        </a> 
                                        <div class="product actions product-item-actions"> 
                                            <?php
                                                $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                                ?> 
                                            <div class="actions-primary">
                                                <?php
                                                    $objectManagerr = \Magento\Framework\App\ObjectManager::getInstance();
                                                    $objBlockk = $objectManagerr->get('\Netbaseteam\Calculatorshipping\Block\Calculatorshipping');
                                                ?>
                                                <?php if($objBlockk->_EnableModule()) : ?>
                                                    <div class="calculator actions-all">
                                                        <a data-product-id="<?php echo $_product->getId(); ?>" class="netbase-calculator netbase_calculator_button netbase-calculator-button" title="Calculator Shipping" >
                                                            <span><i class="icon-truck-1" style="font-size: 18px;"></i></span></a>
                                                    </div>
                                                <?php endif ?>
                                                <?php if ($_product->isSaleable()): ?>
                                                    <?php if ($_product->getTypeInstance()->hasRequiredOptions($_product)): ?>
                                                        <button class="action tocart primary one"
                                                                data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_product) ?>"}}'
                                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php else: ?>
                                                        <?php
                                                            $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper') ; 
                                                            $postDatas = $_helper->getAddToCartPostParams($_product);
                                                            $postData = json_encode($postDatas);
                                                        ?>
                                                        <button class="action tocart primary two"
                                                                data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php endif; ?>
                                                <?php else: ?>
                                                    <?php if ($_product->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                            <?php if ($showWishlist || $showCompare): ?>
                                            <?php 
                                                $objBlock = $objectManagerr->get('\Magento\CatalogWidget\Block\Product\ProductsList');
                                                ?>
                                            <div class="actions-secondary" data-role="add-to-links"> 
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                <a href="#"
                                                    data-post='<?php /* @escapeNotVerified */ echo $objBlock->getAddToWishlistParams($_product); ?>'
                                                    class="action towishlist" data-action="add-to-wishlist"
                                                    title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                <span>Add to Wish List</span>
                                                </a>
                                                <a href="#"
                                                    class="action tocompare"
                                                    title="<?php echo __('Add To Compare'); ?>"
                                                    aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                    data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                                                    role="button"> 
                                                    <span>Compare</span>
                                                </a>
                                                <?php endif; ?>  
                                            </div>
                                            <?php endif; ?> 
                                        </div>
                                    </div>
                                    <div class="product details product-item-details">
                                        <div class="inner-product">
                                            <a title="<?php echo $_product->getName(); ?>" href="<?php echo $_product->getProductUrl() ?>" class="product-item-link">
                                            <?php echo substr($_product->getName(),0,30); ?>
                                            </a>
                                            <?php
                                                $originalPrice = $_product->getData('price')+0;
                                                $finalPrice = $_product->getData('special_price')+0; 
                                                ?>
                                            <div class="price-home <?php if($finalPrice){ echo 'price-sale'; } ?>">
                                                <?php
                                                    if ($finalPrice) {
                                                        echo "<span class='special'>".$_helper->getFormatPrice($finalPrice, 2)."</span>";
                                                    };
                                                    //
                                                    if ($originalPrice) {
                                                        echo "<span class='normal'>".$_helper->getFormatPrice($originalPrice, 2)."</span>";
                                                    }; 
                                                    ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </li> 
                        <?php
                        if ($i == 3) {
                            break;
                        }
                        $i++; endforeach;
                        ?>
                    </ol>
                </div> 
            <?php endforeach; ?>
        </div>

    </div>
</section>
<script type="text/javascript"> </script>