<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?> 
<div class="box-tocart"> 
    <div class="fieldset cart-action">
        <div class="cart-action__title">
            <h3><?= __('Job Summary') ?></h3>
            <p><?= __('See the total pricing and checkout') ?></p>
        </div>
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <div class="control">
               <input type="number"
					   name="qty"
					   id="qty"
					   value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
					   maxlength="12"
					   title="<?php echo __('Qty') ?>"
					   class="input-text qty"
					   data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
				/>
				<div class="control__qty-change">
					<div class="minus"><i class="icon-down-open-big"></i></div>
					<span></span>
					<div class="add"><i class="icon-up-open-big"></i></div>
				</div>                
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
            </button>   
        </div>  
    </div>
</div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
<?php endif; ?>
<script>
    require([
            'jquery',
        ],
        function ($) {
            $('.add').on('click',function(e){
                var $qty=$(this).closest('.control').find('#qty');
                var currentVal = parseInt($qty.val());
                if (!isNaN(currentVal)) {
                    $qty.val(currentVal + 1);
                }
                e.preventDefault();
            });
            $('.minus').on('click',function(e){
                var $qty=$(this).closest('.control').find('#qty');
                var currentVal = parseInt($qty.val());
                if (!isNaN(currentVal) && currentVal > 0) {
                    $qty.val(currentVal - 1);
                }
                e.preventDefault();
            });
        });
</script>
