<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Backend\Block\Page\Header */
?>

<?php
$helper = $this->helper('\Netbaseteam\Themeconfig\Helper\Data');

/************ avanta ************/
$userData = $helper->getAdminUserData();
// $avanta = $helper->getMediaUrl()."avanta/".$userData["username"]."/";	
// $avanta_folder = $helper->getBaseDir()."/avanta/".$userData["username"]."/";
$load_logo_file = "";

$logo = $helper->getMediaUrl()."logo/"; 
$logo_folder = $helper->getBaseDir()."/logo/";
$load_logo_url = "";$load_logo_file = "";

/* read folder ../media/Themeconfig/logo */
if(file_exists($logo_folder)) {
 $files = array_diff(scandir($logo_folder), array('.', '..'));
 foreach($files as $file) {
    $load_logo_file =  $file;
    $load_logo_url = $logo.$file;
    break;
}
}

$class_type = "horizontal_menu";
if($helper->getMenuPosition() == 1) {
    $class_type = "vertical_menu";
} elseif ($helper->getMenuPosition() == 2) {
    $class_type = "vertical_menu_df";
}
?>

<?php switch ($block->getShowPart()):
    case 'logo': ?>
    <?php $edition = $block->hasEdition() ? 'data-edition="' . $block->escapeHtml($block->getEdition()) . '"' : ''; ?>
    <?php $logoSrc = ($block->hasLogoImageSrc()) ? $block->escapeHtml($block->getLogoImageSrc()) : 'images/login-logo.png' ?>
    <a
    href="<?php /* @escapeNotVerified */ echo $block->getHomeLink() ?>"
    <?php /* @escapeNotVerified */ echo $edition; ?>
    class="logo">
    <img class="logo-img" src="<?php /* @escapeNotVerified */ if($load_logo_url != "") { echo $load_logo_url; } else { echo $block->getViewFileUrl($logoSrc); } ?>" data-default="<?php echo $block->getViewFileUrl($logoSrc); ?>"
    alt="<?php echo $block->escapeHtml(__('Magento Admin Panel')) ?>"/>
</a>
<a href="#" class="button-close-menu pe-7s-close-circle"></a>
<?php break; ?>
<?php case 'user': ?>
<div class="admin-user admin__action-dropdown-wrap">
    <a
    href="<?php /* @escapeNotVerified */ echo $block->getUrl('adminhtml/system_account/index') ?>"
    class="admin__action-dropdown"
    title="<?php echo $block->escapeHtml(__('My Account')) ?>"
    data-mage-init='{"dropdown":{}}'
    data-toggle="dropdown">
    <span class="admin__action-dropdown-text">
        <span class="admin-user-account-text"><?php echo $block->escapeHtml($block->getUser()->getUsername()); ?></span>
    </span>
</a>
<ul class="admin__action-dropdown-menu">
    <?php if ($block->getAuthorization()->isAllowed('Magento_Backend::myaccount')): ?>
    <li>
        <a
        href="<?php /* @escapeNotVerified */ echo $block->getUrl('adminhtml/system_account/index') ?>"
        <?php /* @escapeNotVerified */ echo $block->getUiId('user', 'account', 'settings')?>
        title="<?php echo $block->escapeHtml(__('Account Setting')) ?>">
        <?php /* @escapeNotVerified */ echo __('Account Setting') ?> (<span class="admin-user-name"><?php echo $block->escapeHtml($block->getUser()->getUsername()); ?></span>)
    </a>
</li>
<?php endif; ?>
<li>
    <a
    href="<?php /* @escapeNotVerified */ echo $block->getBaseUrl(); ?>"
    title="<?php echo $block->escapeHtml(__('Customer View')); ?>"
    target="_blank" class="store-front">
    <?php /* @escapeNotVerified */ echo __('Customer View'); ?>
</a>
</li>
<li>
    <a
    href="<?php /* @escapeNotVerified */ echo $block->getLogoutLink() ?>"
    class="account-signout"
    title="<?php echo $block->escapeHtml(__('Sign Out')) ?>">
    <?php /* @escapeNotVerified */ echo __('Sign Out') ?>
</a>
</li>
</ul>
</div>
<div class="menu-icon">
    <i class="pe-7s-menu"></i>
</div>
<?php break; ?>
<?php case 'other': ?>
<?php echo $block->getChildHtml(); ?>
<?php break; ?>
<?php endswitch; ?>
<script type="text/javascript">
    require(['jquery'], function($) {
        $(document).ready(function($) {
            var w = window.screen.width;
            var uA = navigator.userAgent;
            var class_menu = '<?php echo $class_type; ?>';
            if(uA.indexOf('Trident') != -1 && uA.indexOf('rv:11') != -1){   
                $('body').addClass('ie');
            } 
            else if(navigator.userAgent.indexOf("Firefox")!=-1){
                $('body').addClass('firefox');
            }
            else if(navigator.userAgent.indexOf("Opera")!=-1){
                $('body').addClass('Opera');
            }
            else if(navigator.userAgent.indexOf("Chrome") != -1){ 
                $('body').addClass('chrome');
            }
            else if(navigator.userAgent.indexOf("Safari")!=-1){
                $('body').addClass('safari');
            }

            if ($('.admin_group-field-menu .field-admin-radio').length>0) {
                $('.admin_group-field-menu .field-admin-radio #<?php echo $class_type; ?>').attr("checked", "checked");
            }

            if (w>991) {
                $('body').addClass(class_menu);
            } else {
                $('body').addClass('vertical_menu_df');
                if (class_menu!='vertical_menu_df') {
                    $('body').addClass('menu_changed');
                }
            }
            
        });
    });
</script>